const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Baaba Devs";
const email = 'Email';
const password = 'Password';
const passwordhint = '******';
const retyppassword = 'RetypePassword';
const name = 'Name';
const namehint = 'M .Elkouny';
const emailHint = 'admin@admin.com';
const forgPassword = 'Forget Password';
const login = 'Log in';
const logined = 'Logged in Successefully';
const logout = 'Logged Out Successefully';

const signup = 'SignUp';
const createNewAcocount = "or,Create New Acoount";
const loginWith = "Login in With";
const privcyPolicy = "Privacy Policy ";
const termsAndcond = "Terms and Conditions ";
const alreadyHaveAccount = "Already Have An Account ? ";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const search = 'Search Any Thing',
    today = "Today's Deal",
    brand = "Brand",
    flashsale = "Flash Sale",
    topseller = "Top Sellers",
    womendre = "Women Dress",
    girlwatch = "Girls Watches",
    mobiephone = "Mobile Phone",
    boysglasses = "Boys Glasses",
    tshirts = "TShirts",
    girlsdress = "Girls Dresses",
    topcategory = "Top Catogries",
    featuredcategory = "Featured Catogries",
    featuredproduct = "Featured Product";
const womenclothing = "Women Clothing",
    menclothingfashion = "Men Clothing & Fashion",
    compAcess = "Computer & Accessories",
    automobile = "Automobile",
    kidstoys = 'Kids & Toys',
    sports = "Sports",
    jewellery = "Jewelery",
    cellphone = "CellPhone & Tab",
    furniture = "Furniture";
const video = "Video",
    review = "Reviews",
    sellerpolicy = "Seller Policy",
    returnpolity = "Return Policy",
    supportpolicy = "Support Policy",
    productsyoumylike = "Products You May Like";
const wishlist = "My Wishlist",
    orders = "My Orders",
    message = "My Messages",
    oldpass = "Old Password",
    newpassword = 'New Password';
