// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9S3JFsOkw6yxHVJeV7kY9LuX9abs3UvY',
    appId: '1:376965746848:web:f437fb7dea50fa1e49b9c5',
    messagingSenderId: '376965746848',
    projectId: 'emart-181a5',
    authDomain: 'emart-181a5.firebaseapp.com',
    storageBucket: 'emart-181a5.appspot.com',
    measurementId: 'G-XZ37GR0LF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlPQ46hElGxjBKPlGa6cVdfaZ9ZjL3hwQ',
    appId: '1:376965746848:android:85982c4a7dd0d65749b9c5',
    messagingSenderId: '376965746848',
    projectId: 'emart-181a5',
    storageBucket: 'emart-181a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPnDHH5bpfTQSimzlpqjKdC_KQJXKgmmE',
    appId: '1:376965746848:ios:51fc42954e30d87d49b9c5',
    messagingSenderId: '376965746848',
    projectId: 'emart-181a5',
    storageBucket: 'emart-181a5.appspot.com',
    iosBundleId: 'com.example.emart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPnDHH5bpfTQSimzlpqjKdC_KQJXKgmmE',
    appId: '1:376965746848:ios:dc392c7401c9e32d49b9c5',
    messagingSenderId: '376965746848',
    projectId: 'emart-181a5',
    storageBucket: 'emart-181a5.appspot.com',
    iosBundleId: 'com.example.emart.RunnerTests',
  );
}
